name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: version
        name: Check and set version outputs
        run: |
          set -xe

          VERSION="$(cat VERSION)"
          grep '"version": "'"${VERSION}"'",$' library.json
          grep "^version=${VERSION}" library.properties

          echo "filename=RaiseDev-${VERSION}.tar.gz" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: pip install --upgrade platformio
      - run: pio ci --project-conf=platformio.ini --lib=. examples
      - run: pio pkg pack --output="${{ steps.version.outputs.filename }}"
      - run: pio pkg publish --no-interactive --owner=raisedevs --type=library "${{ steps.version.outputs.filename }}"
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
